services:
  docker-database-volume-backup:
    image: docker-database-volume-backup:dev
    environment:
      - TZ=Europe/Berlin # Define your timezone here
      # You can also use environment variable without docker secrets
      # (i.e. via MYSQL_HOST=...) but that is highly discouraged.
      - MYSQL_HOST_FILE=/run/secrets/backup_mysql_host
      - MYSQL_USER_FILE=/run/secrets/backup_mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/backup_mysql_password
      - MYSQL_DATABASE_FILE=/run/secrets/backup_mysql_database
      - BASIC_AUTH_USER=test
      - BASIC_AUTH_PASSWORD=test
      - BACKUP_ON_START=true
      - BACKUP_CRON=@every 1h
      - BACKUP_KEEP=5
    secrets:
      - backup_mysql_host
      - backup_mysql_user
      - backup_mysql_password
      - backup_mysql_database
    volumes:
      - "./backups:/backups" # Backups will be stored here
      - "<path_to_your_volume>:/files" # Which filepath to backup
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8080:8080"
    networks:
      - mysql-net

networks:
  mysql-net:
    external: true

secrets:
  backup_mysql_host:
    external: true
  backup_mysql_user:
    external: true
  backup_mysql_password:
    external: true
  backup_mysql_database:
    external: true
